//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public Nullable<int> adults { get; set; }
        public Nullable<int> children { get; set; }
        public int room_type { get; set; }
        public int meal_id { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public int room_Num { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Room Room { get; set; }
        public virtual Room_Type Room_Type1 { get; set; }
    }
}
