//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Divers_HotelEntities : DbContext
    {
        public Divers_HotelEntities()
            : base("name=Divers_HotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder ModelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Room_Type> Room_Type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
